### ISSUE TITLE
Build Rejected

### ISSUE THREAD

**Issue by RajChanchal** [dimat/DMNumberSpellOutFormatter#1]
Hi, I submitted a build to AppStore it got rejected because of following issues:

We have discovered one or more issues with your recent delivery for "ZamCGs". To process your delivery, the following issues must be corrected:
Non-public API usage:
• The app references non-public symbols in Frameworks/NumberSpellOutFormatter.framework/NumberSpellOutFormatter: unum_close, unum_format, unum_getTextAttribute, unum_open, _unum_setTextAttribute
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

**Comment by dimat** [comment]
Hey. Yes, I’m aware of this and I mentioned this on the main readme. But I already have a custom build of the icu4c that resolves this problem. I had a few problems with integrating it into cocoapods. Will look at it tonight and if it all works then will push the update

**Comment by dimat** [comment]
I've just pushed the version `0.2` that includes precompiled icu4c and it doesn't reference to the iOS private APIs anymore.

**Comment by dimat** [comment]
@RajChanchal once you resubmit the app, could you please drop a message here if it gets approved? Would be good to know :)

**Comment by RajChanchal** [comment]
Thanks for following up the issue, I’ll let you know.
